elCicdChart:
  parameters:
    INSTANCE_1: instance1
    INSTANCE_2: instance2
    CPU_UTILIZATION: 90
    MIN_REPLICAS: 1
    MAX_REPLICAS: 3
    TOPIC: topic
    TOPIC_NAME: topicname
    CGROUP: cgroup
    INSTANCE_2_PORT: 8082
    ENV_DEF:
    - name: ${TOPIC_NAME}
      value: ${INSTANCE_1}-${TOPIC}
    - name: password
      valueFrom:
        secretKeyRef:
          key: password
          name: ${MICROSERVICE_NAME}-sealed-secret
    - name: ${TOPIC_NAME}
      valueFrom:
        configMapKeyRef:
          key: ${TOPIC_NAME}
          name: ${APP_NAME}-configmap
    - name: ${CGROUP}
      ${CGROUP_VALUE_DEF_KEY}: ${CGROUP_VALUE_DEF}
    CGROUP_VALUE_DEF_KEY: valueFrom
    CGROUP_VALUE_DEF:
      configMapKeyRef:
        key: ${CGROUP}
        name: ${APP_NAME}-configmap
    DATA_MAP:
      ${CGROUP}: ${CGROUP}
      ${TOPIC_NAME}: ${SDLC_ENV}-${APP_NAME}-${TOPIC}
      ${TEST_KEY}: ${TEST_VALUE}
    
  parameters-dev:
    CPU_UTILIZATION: 150
    MAX_REPLICAS: 2
    
  parameters-prod:
    MIN_REPLICAS: 2
    MAX_REPLICAS: 5

  templates:
  - templateName: deploymentService
    appName: ${MICROSERVICE_NAME}-${INSTANCE_1}
    env: ${ENV_DEF}
    parameters:
      CGROUP: cgroup-overridden
    parameters-dev:
      CGROUP_VALUE_DEF_KEY: value
      CGROUP_VALUE_DEF: patch-test-${SDLC_ENV}-${INSTANCE_1}

  - templateName: configMap
    appName: ${MICROSERVICE_NAME}-${INSTANCE_1}-configmap
    data: ${DATA_MAP}

  - templateName: ingress
    appName: ${MICROSERVICE_NAME}-${INSTANCE_1}

  - templateName: horizontalPodAutoscaler
    appName: ${MICROSERVICE_NAME}-${INSTANCE_1}
    maxReplicas: ${MAX_REPLICAS}
    minReplicas: ${MIN_REPLICAS}
    metrics:
    - type: Resource
      name: cpu
      target:
        type: Utilization
        averageUtilization: ${CPU_UTILIZATION}

  - templateName: deploymentService
    appName: ${MICROSERVICE_NAME}-${INSTANCE_2}
    env: ${ENV_DEF}
    port: ${INSTANCE_2_PORT}

  - templateName: configMap
    appName: ${MICROSERVICE_NAME}-${INSTANCE_2}-configmap
    parameters-dev:
      TEST_KEY: my-test-key
      TEST_VALUE: just-for-this-map
    data: ${DATA_MAP}

  - templateName: ingress
    appName: ${MICROSERVICE_NAME}-${INSTANCE_2}
    port: ${INSTANCE_2_PORT}
