
templates-dev:
- templateName: deploymentService
  appName: ${MICROSERVICE_NAME}-${INSTANCE_1}  
  env:
  - name: cgroup
    value: patch-test-${SDLC_ENV}-${INSTANCE_1}
- templateName: deploymentService
  appName: ${MICROSERVICE_NAME}-${INSTANCE_2}  
  env: 
  - name: cgroup
    value: patch-test-${SDLC_ENV}-${INSTANCE_2}