templateVars:
  INSTANCE_1: instance1
  INSTANCE_2: instance2
  CPU_UTILIZATION: 90
  MIN_REPLICAS: 1
  MAX_REPLICAS: 3
  TOPIC: topic
  TOPIC_NAME: topicname
  
templateVars-qa:
  CPU_UTILIZATION: 50
  MAX_REPLICAS: 2
  
templateVars-prod:
  MIN_REPLICAS: 2
  MAX_REPLICAS: 5

templates:
- templateName: deploymentService
  appName: ${MICROSERVICE_NAME}-${INSTANCE_1}  
  env:
  - name: ${TOPIC_NAME}
    value: ${INSTANCE_1}-${TOPIC}
  - name: password
    valueFrom:
      secretKeyRef:
        key: password
        name: ${MICROSERVICE_NAME}-sealed-secret
  - name: ${TOPIC_NAME}
    valueFrom:
      configMapKeyRef:
        key: ${TOPIC_NAME}
        name: ${APP_NAME}-configmap
  - name: cgroup
    valueFrom:
      configMapKeyRef:
        key: cgroup
        name: ${APP_NAME}-configmap
- templateName: ingress
  appName: ${MICROSERVICE_NAME}-${INSTANCE_1}
- templateName: configMap
  appName: ${MICROSERVICE_NAME}-${INSTANCE_1}-configmap
  data:
    ${TOPIC_NAME}: ${SDLC_ENV}-${INSTANCE_1}-${TOPIC}
- templateName: horizontalPodAutoscaler
  appName: ${MICROSERVICE_NAME}-${INSTANCE_1}
  maxReplicas: ${MAX_REPLICAS}
  minReplicas: ${MIN_REPLICAS}
  metrics:
  - type: Resource
    name: cpu
    target:
      type: Utilization
      averageUtilization: ${CPU_UTILIZATION}
- templateName: deploymentService
  appName: ${MICROSERVICE_NAME}-${INSTANCE_2}
  env:
  - name: ${TOPIC_NAME}
    value: ${INSTANCE_2}-${TOPIC}
  port: 8082
- templateName: ingress
  appName: ${MICROSERVICE_NAME}-${INSTANCE_2}
  port: 8082
- templateName: configMap
  appName: ${MICROSERVICE_NAME}-${INSTANCE_2}-configmap
  file: configmap-template.yaml
  data:
  - name: ${TOPIC_NAME}
    value: ${SDLC_ENV}-${INSTANCE_2}-${TOPIC}
